{
 "title": "triton Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "url",
    "query": {
     "query": "SHOW TAG VALUES FROM \"prome_triton\" WITH KEY = \"url\" WHERE time > now() - 30s"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_model",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "model::tag" ], "type": "tag" }
     ],
     "measurement": "prome_triton",
     "query": "SELECT non_negative_derivative(last(\"nv_inference_count\"), 1s)\nFROM \"prome_triton\"\nWHERE $timeFilter\nGROUP BY time(1s), \"model\"::tag",
     "select": [
      [
       { "params": [ "nv_inference_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Avg Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "alias": "$tag_model",
     "query": "SELECT\n    non_negative_derivative(SUM(\"nv_inference_request_duration_us\"), 1s) /\n    non_negative_derivative(SUM(\"nv_inference_exec_count\"), 1s)\nFROM \"prome_triton\"\nWHERE $timeFilter\nGROUP BY time(1s), \"model\"::tag"
    }
   ]
  },
  {
   "title": "Fail percentile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_model",
     "query": "SELECT non_negative_derivative(last(\"nv_inference_request_failure\"), 1s) / non_negative_derivative(last(\"nv_inference_count\"), 1s)\nFROM \"prome_triton\"\nWHERE $timeFilter\nGROUP BY time(1s), \"model\"::tag"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_triton",
     "query": "SELECT moving_average(mean(\"nv_gpu_utilization\"), 5) FROM \"prome_triton\" WHERE $timeFilter GROUP BY time($__interval), \"url\"::tag fill(null)",
     "select": [
      [
       { "params": [ "nv_gpu_utilization" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pending requests num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "alias": "$tag_model",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "model::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_triton",
     "select": [
      [
       {
        "params": [
         "nv_inference_pending_request_count"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU memory use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_triton",
     "query": "SELECT moving_average(mean(\"nv_gpu_memory_used_bytes\"), 5)  / 1024/1024 FROM \"prome_triton\" WHERE $timeFilter GROUP BY time($__interval), \"gpu_uuid\"::tag fill(null)",
     "select": [
      [
       { "params": [ "nv_gpu_memory_used_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         5
        ],
        "type": "moving_average"
       },
       { "params": [ " / 1024/1024/1024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Total Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_triton",
     "query": "SELECT mean(\"nv_gpu_memory_used_bytes\")/1024/1024 FROM \"prome_triton\" WHERE $timeFilter GROUP BY time($__interval), \"host\"::tag",
     "select": [
      [
       { "params": [ "nv_gpu_memory_total_bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1024/1024" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "url" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_triton",
     "query": "SELECT max(\"nv_gpu_power_usage\") FROM \"\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "nv_gpu_power_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}