{
 "title": "vLLM Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "decoing time per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT\n    non_negative_derivative(SUM(\"vllm:request_decode_time_seconds_sum\"), 1s) /\n    non_negative_derivative(SUM(\"vllm:request_decode_time_seconds_count\"), 1s)\nFROM \"prome_vllm\"\nWHERE $timeFilter  \nGROUP BY time(1s), \"model_name\"::tag,\"url\"::tag"
    }
   ]
  },
  {
   "title": "e2e avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_model_name",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_vllm",
     "query": "SELECT non_negative_derivative(SUM(\"vllm:e2e_request_latency_seconds_sum\"), 1s)/ non_negative_derivative(SUM(\"vllm:e2e_request_latency_seconds_count\"), 1s) FROM \"prome_vllm\" WHERE $timeFilter GROUP BY time(1s),\"model_name\"::tag fill(null)",
     "select": [
      [
       {
        "params": [
         "vllm:request_inference_time_seconds_sum"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "qps ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT\n    non_negative_derivative(last(\"vllm:time_to_first_token_seconds_count\"), 1s) \nFROM \"prome_vllm\"\nWHERE $timeFilter  \nGROUP BY time(1s), \"model_name\"::tag,\"url\"::tag"
    }
   ]
  },
  {
   "title": "Output Tokens per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "alias": "$tag_url.__.$tag_model_name",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_vllm",
     "query": "SELECT non_negative_derivative(last(\"vllm:generation_tokens_total\"), 1s) FROM \"prome_vllm\" WHERE $timeFilter GROUP BY time(1s), \"model_name\"::tag, \"url\"::tag fill(null)",
     "select": [
      [
       { "params": [ "vllm:generation_tokens_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "avg Time to First token",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT\n    non_negative_derivative(SUM(\"vllm:time_to_first_token_seconds_sum\"), 1s) /\n    non_negative_derivative(SUM(\"vllm:time_to_first_token_seconds_count\"), 1s)\nFROM \"prome_vllm\"\nWHERE $timeFilter  \nGROUP BY time(1s), \"model_name\"::tag,\"url\"::tag"
    }
   ]
  },
  {
   "title": "Prompt Token Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_vllm",
     "select": [
      [
       { "params": [ "vllm:prompt_tokens_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "avg inter token latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_model_name._.$tag_url",
     "query": "SELECT\n    non_negative_derivative(SUM(\"vllm:inter_token_latency_seconds_sum\"), 1s) /\n    non_negative_derivative(SUM(\"vllm:inter_token_latency_seconds_count\"), 1s)\nFROM \"prome_vllm\"\nWHERE $timeFilter  \nGROUP BY time(1s), \"model_name\"::tag,\"url\"::tag"
    }
   ]
  },
  {
   "title": "prefill avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "SELECT\n    non_negative_derivative(SUM(\"vllm:request_prefill_time_seconds_sum\"), 1s) /\n    non_negative_derivative(SUM(\"vllm:request_prefill_time_seconds_count\"), 1s)\nFROM \"prome_vllm\"\nWHERE $timeFilter  \nGROUP BY time(1s), \"model_name\"::tag,\"url\"::tag"
    }
   ]
  },
  {
   "title": "generation token per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "$tag_model_name._.$tag_url",
     "query": "SELECT\n    non_negative_derivative(SUM(\"vllm:request_generation_tokens_sum\"), 1s) /\n    non_negative_derivative(SUM(\"vllm:request_generation_tokens_count\"), 1s)\nFROM \"prome_vllm\"\nWHERE $timeFilter  \nGROUP BY time(1s), \"model_name\"::tag,\"url\"::tag"
    }
   ]
  },
  {
   "title": "Running Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "$tag_model_name._.$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "model_name::tag" ], "type": "tag" },
      { "params": [ "url::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_vllm",
     "query": "SELECT mean(\"vllm:num_requests_running\") FROM \"prome_vllm\" WHERE $timeFilter GROUP BY time($__interval), \"model_name\"::tag fill(null)",
     "select": [
      [
       { "params": [ "vllm:num_requests_running" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "pending requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "alias": "$tag_model_name._.$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "model_name::tag" ], "type": "tag" },
      { "params": [ "url::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_vllm",
     "select": [
      [
       { "params": [ "vllm:num_requests_waiting" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "prompt tokens per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "alias": "$tag_model_name._.$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_vllm",
     "query": "SELECT\n    non_negative_derivative(SUM(\"vllm:request_prompt_tokens_sum\"), 1s) /\n    non_negative_derivative(SUM(\"vllm:request_prompt_tokens_count\"), 1s)\nFROM \"prome_vllm\"\nWHERE $timeFilter  \nGROUP BY time(1s), \"model_name\"::tag,\"url\"::tag",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}