FROM ubuntu:22.04

RUN rm -rf /etc/apt/sources.list.d
ADD external-files/sources.list_image22 /etc/apt/sources.list
ADD external-files/uv.toml /root/.config/uv/uv.toml

# Set timezone
ENV DEBIAN_FRONTEND=noninteractive
RUN echo 'tzdata tzdata/Areas select Asia' | debconf-set-selections \ 
    && echo 'tzdata tzdata/Zones/Asia select Shanghai' | debconf-set-selections \ 
    && apt update && apt install -y tzdata git curl vim wget mysql-server gnupg \ 
    && curl -LsSf https://astral.sh/uv/install.sh | sh \ 
    && /root/.local/bin/uv venv /opt/venv --python 3.12 \ 
    && rm -f /usr/bin/python3 /usr/bin/python3-config /usr/bin/pip \ 
    && ln -sf /opt/venv/bin/python3 /usr/bin/python3 \ 
    && ln -sf /opt/venv/bin/python3 /usr/bin/python \ 
    && ln -sf /opt/venv/bin/python3-config /usr/bin/python3-config \ 
    && ln -sf /opt/venv/bin/pip /usr/bin/pip \ 
    && python3 --version && python3 -m pip --version

ENV PATH=/opt/venv/bin:/root/.local/bin/:/usr/bin/:$PATH

RUN uv pip install requests ipython

# grafana
RUN cd /tmp && apt-get install -y adduser libfontconfig1 musl \
    && wget -q https://dl.grafana.com/grafana/release/12.3.0/grafana_12.3.0_19497075765_linux_amd64.deb \
    && dpkg -i grafana_12.3.0_19497075765_linux_amd64.deb \
    && rm -rf /tmp/*

# telegraf
RUN cd /tmp && mkdir -p /etc/apt/sources.list.d && curl --silent --location -O https://repos.influxdata.com/influxdata-archive.key \
    && cat influxdata-archive.key  | gpg --dearmor  | tee /etc/apt/keyrings/influxdata-archive.gpg > /dev/null \
    && echo 'deb [signed-by=/etc/apt/keyrings/influxdata-archive.gpg] https://repos.influxdata.com/debian stable main' | tee /etc/apt/sources.list.d/influxdata.list \
    && apt-get update && apt-get install telegraf -y \
    && apt clean \
    && rm /tmp/*
    
# # VictoriaMetrics
RUN cd /tmp && mkdir -p /opt/VM/ && wget -q https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/v1.106.0/victoria-metrics-linux-amd64-v1.106.0.tar.gz \
    && tar -C /opt/VM -xzf victoria-metrics-linux-amd64-v1.106.0.tar.gz \
    && rm -rf /tmp/*

ENV PATH=/opt/VM:$PATH


WORKDIR /workspace