{
 "title": "tei Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "input length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_tei",
     "query": "SELECT\n    non_negative_derivative(SUM(\"te_request_input_length_sum\"), 1s) /\n    non_negative_derivative(SUM(\"te_request_input_length_count\"), 1s)\nFROM \"prome_tei\"\nWHERE $timeFilter  \nGROUP BY time(1s), \"url\"::tag",
     "select": [
      [
       { "params": [ "te_request_input_length_sum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "qps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "prome_tei",
     "query": "SELECT non_negative_derivative(last(\"te_request_duration_count\"), 1s) \nFROM \"prome_tei\" \nWHERE $timeFilter \nGROUP BY time(1s), \"url\"::tag fill(null)",
     "select": [
      [
       { "params": [ "te_request_count" ], "type": "field" },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "avg latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_url",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "url::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_tei",
     "query": "SELECT non_negative_derivative(SUM(\"te_request_duration_sum\"), 1s) / non_negative_derivative(SUM(\"te_request_duration_count\"), 1s) FROM \"prome_tei\" WHERE $timeFilter GROUP BY time(1s), \"url\"::tag fill(null)",
     "select": [
      [
       { "params": [ "te_request_duration_sum" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "prome_tei",
     "select": [
      [
       { "params": [ "te_queue_size" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fail Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_url",
     "query": "SELECT non_negative_derivative(SUM(\"te_request_failure\"), 1s) / non_negative_derivative(SUM(\"te_request_count\"), 1s)\nFROM \"prome_tei\"\nWHERE $timeFilter\nGROUP BY time(1s), \"url\"::tag"
    }
   ]
  }
 ]
}